# Generated by Django 3.1.5 on 2021-03-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='online',
            field=models.IntegerField(blank=True, max_length=2, null=True),
        ),
    ]
